name: Python Package Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim
      env:
        NODE_VERSION: 20

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create virtual environment
      run: python -m venv venv

    - name: Activate virtual environment
      run: |
        . venv/bin/activate

    - name: Install dependencies
      run: |
        venv/bin/python -m pip install --upgrade pip
        venv/bin/python -m pip install pytest
        venv/bin/python -m pip install -r requirements.txt

    - name: Test with pytest
      run: |
        venv/bin/python -m pytest tests
