name: Version Branch CI/CD

on:
  pull_request:
    branches: ["v*"]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4.1.6
      with:
        fetch-depth: 0
    - name: Install the latest version of Rye
      uses: eifinger/setup-rye@v3.0.2
    - name: Setup the environment
      run: rye sync --all-features
    - name: Test with pytest
      run: rye run pytest --cov=agogos --cov-branch --cov-fail-under=95 tests

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4.1.6
    - name: Install the latest version of Rye
      uses: eifinger/setup-rye@v3.0.2
    - name: Build the package
      run: rye build
    - uses: actions/upload-artifact@v4.3.3
      with:
        path: ./dist
